#!/bin/bash

# Use the ps command to display process information
# -e: Select all processes
# -ww: Wide output to ensure that long command lines are not truncated
# -o: Custom output format
#    user: User owning the process
#    pid: Process ID
#    %cpu: CPU usage
#    %mem: Memory usage
#    vsz: Virtual memory size
#    rss: Resident set size
#    tty: Terminal associated with the process
#    stat: Process status
#    start: Start time or date
#    time: Cumulative CPU time
#    args: Command with all its arguments
ps aux

