#!/bin/bash

# Run the "4-to_infinity_and_beyond" process in the background
./4-to_infinity_and_beyond &

# Store the PID of the process
pid=$!

# Sleep for a while to allow the process to run
sleep 5

# Stop the process
kill "$pid" > /dev/null 2>&1

# Check if the process is still running
if ps -p "$pid" > /dev/null; then
	echo "Process is still running"
else
	echo "Terminated"
fi

