#!/bin/bash

# Retrieve the list of active network interfaces
interfaces=$(ip -4 -o addr show | awk '{print $2}')

# Iterate over each interface and display the associated IPv4 address
for interface in $interfaces; do
	# Extract the IPv4 address using regex
	ipv4=$(ip -4 -o addr show dev $interface | awk '{print $4}' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')

	      # Display the IPv4 address if it's not empty
	      if [ -n "$ipv4" ]; then
		      echo "$ipv4"
	      fi
      done

